language: node_js

node_js:
  - 'v6'

cache:
  directories:
    - node_modules

deploy:
  - provider: script
    script: npm run deploy
    on:
      tags: true

script: true

env:
  global:
    - BUCKET=benjaminwarfield
    - CF_DISTRIBUTION=E3QZ67O0O7WU4S
    - AWS_ACCESS_KEY_ID=AKIAI5JOYIR5PR3MYDUQ
    - secure: "K2UeG/Jj2g5ToH6HwNDnVELv9+MDqwQKkOHjUvPYTzfwJYP8VuCR0GwuDwT0IWy9r9KRqpKpUZVLev7t2AVs1hXjyNgDijTniaGWA3ogn5YBlfawvuHCMwA4SvF6VZ4ZNaGhBUhlOLGpPSkYtTohTJbdfc53PaTFYoR0DjAo8FU4A9QSLFrF02kAoF4Lv0iHB9HhGLsL8i7OhUL8cey/bfBTupPaELQEyRDS+wUPilIJz4VUpFGIhr6/bu0pXdExUubqw7Kz9RWhv/Hh3tadnGCENjzyPj7fa1IYGYGJvZbpMsI3pTASDcnjD1jIkDG0V/Gy5rKJSQxo6pESoFWl0dU5XpJ5vAH4uELxaG+viZFTiquW7njRb4jN08OVQfbozjY0REHvRsYMXdhNm7Syw4pP38+4Slb1uFxq+M/W23dY+fJ/LKCm2F6pIzqYaqeTxdjAS3Dd2JlQWvIyjpc/pPqASM30a+E6QA1tB/FrS7yl3jqa1l+vyhcmxgCtHO4fKKZWNik1551K7zf0bf21qGFdCK3DfwUGwtMgywv9UWwbG2KdTe7R8NigxylAsoAYJaIrC8PNqCRr61b+HXWaedieqr9r+107kEsuDjM9RgFzessz8pyulDaXp6v6vobIolAdZogYznPX34wa7Q9NSiWEBkLe3Z5H4BvLovlNW08="
